require 'rails_helper'
require 'spec_helper'

describe Debt, :type => :model do
  fixtures :users

  before(:each) do
    @debt = Debt.new(
      :description => 'An expense',
      :amount => 1000,
      :loaner => users(:complete),
      :collector => users(:complete)
    )
  end

  describe 'autogenerated values' do
    it 'should be uuid' do
      expect(@debt.uuid).to_not be_nil
    end
  end

  describe 'required parameters' do
    it 'should be amount parameter' do
      # given
      @debt.amount = nil
      # when
      result = @debt.save
      # then
      expect(result).to be(false)
    end

    it 'should be description parameter' do
      # given
      @debt.description = nil
      # when
      result = @debt.save
      # then
      expect(result).to be(false)
    end

    it 'should be loaner parameter' do
      # given
      @debt.loaner = nil
      # when
      result = @debt.save
      # then
      expect(result).to be(false)
    end

    it 'should be collector parameter' do
      # given
      @debt.collector = nil
      # when
      result = @debt.save
      # then
      expect(result).to be(false)
    end
  end
end
