require 'rails_helper'
require 'spec_helper'

describe Transaction, :type => :model do
  fixtures :users

  before(:each) do
    @transaction = Transaction.new(
      :description => 'An expense',
      :balance => 1000,
      :recipient => users(:complete),
      :sender => users(:complete)
    )
  end

  describe 'autogenerated values' do
    it 'should be uuid' do
      expect(@transaction.uuid).to_not be_nil
    end
  end

  describe 'required parameters' do
    it 'should be balance parameter' do
      # given
      @transaction.balance = nil
      # when
      result = @transaction.save
      # then
      expect(result).to be(false)
    end

    it 'should be description parameter' do
      # given
      @transaction.description = nil
      # when
      result = @transaction.save
      # then
      expect(result).to be(false)
    end

    it 'should be recipient parameter' do
      # given
      @transaction.recipient = nil
      # when
      result = @transaction.save
      # then
      expect(result).to be(false)
    end

    it 'should be sender parameter' do
      # given
      @transaction.sender = nil
      # when
      result = @transaction.save
      # then
      expect(result).to be(false)
    end
  end
end
