# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f022d9260b089c95ae3d9ca39a95dc5ce18dded55c2edac65fba4005ed3a4af06d45736679e438954befcd7e0286e3969251f0fc862c322dd66600279a07f5a

test:
  secret_key_base: e5c13e4af184e2f920bcd68a061990da3acb97b1bc018c735c6968f77d78a7e3d881dc27a1fe35f9c41f57e8ac6a5d4a9b20353e09d9145c4ac714ca7f0490b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
